### ISSUE TITLE
e chào ah

### ISSUE THREAD

**Issue by phamvanhai208** [generaltrung/GetLinkFshare#1]
hiện e có sử dụng code do ah viết thì bị lỗi như thế này ạ e không biết sai chỗ nào mong ah chỉ giúp e ạ
Traceback (most recent call last):
  File "/content/getlinkfshare/getlinkFshare.py", line 72, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/getlinkfshare/getlinkFshare.py", line 39, in download
    download_link = fshare.get_link(link_paras[0], passwd)
  File "/content/getlinkfshare/fshare.py", line 49, in get_link
    ispass = int(self.get_link_info(url)['current']['pwd'])
KeyError: 'current'

**Comment by generaltrung** [comment]
Chào bạn, mục đích ban đầu khi viết script này là mình muốn getlink Fshare sử dụng account VIP sẵn có của mình. 
Sau 1 thời gian thì chức năng này chuyển qua file folder_downloader.py nhé, cũng là function get_link. 
Điều kiện: có sẵn acc acount Fshare VIP. Mình viết tool này xuất phát từ nhu cầu thực tế của riêng mình, nên chưa test vs account Fshare thường :)

Thanks

**Comment by phamvanhai208** [comment]
E cũng sử dụng acc vip của mình nhưng khi vào tới phần dow là nó bị lỗi còn mấy phần kia vẫn ok ạ.

Được gửi từ Thư<https://go.microsoft.com/fwlink/?LinkId=550986> dành cho Windows 10

Từ: Nguyễn Lê Hoàng Trung<mailto:notifications@github.com>
Đã gửi: 11 Tháng Mười 2020 4:32 CH
Đến: generaltrung/GetLinkFshare<mailto:GetLinkFshare@noreply.github.com>
Cc: phamvanhai208<mailto:phamvanhai208@hotmail.com>; Author<mailto:author@noreply.github.com>
Chủ đề: Re: [generaltrung/GetLinkFshare] e chào ah (#1)


Chào bạn, mục đích ban đầu khi viết script này là mình muốn getlink Fshare sử dụng account VIP sẵn có của mình.
Sau 1 thời gian thì chức năng này chuyển qua file folder_downloader.py nhé, cũng là function get_link.
Điều kiện: có sẵn acc acount Fshare VIP. Mình viết tool này xuất phát từ nhu cầu thực tế của riêng mình, nên chưa test vs account Fshare thường :)

Thanks

**Comment by generaltrung** [comment]
Bạn chạy script cú pháp như thế nào? Dưới đây là cú pháp đúng cho việc get_link
folder_downloader.py get_link "https://www.fshare.vn/file/QAYQK9DQC6L9"
hoặc folder_downloader.py get_link "https://www.fshare.vn/file/QAYQK9DQC6L9|blablabla" vs link có password

**Comment by phamvanhai208** [comment]
Dạ anh ơi link bị lỗi rồi ạ anh cho e xin lại link với nha


Được gửi từ Thư<https://go.microsoft.com/fwlink/?LinkId=550986> dành cho Windows 10

Từ: Nguyễn Lê Hoàng Trung<mailto:notifications@github.com>
Đã gửi: 11 Tháng Mười 2020 10:28 CH
Đến: generaltrung/GetLinkFshare<mailto:GetLinkFshare@noreply.github.com>
Cc: phamvanhai208<mailto:phamvanhai208@hotmail.com>; Author<mailto:author@noreply.github.com>
Chủ đề: Re: [generaltrung/GetLinkFshare] e chào ah (#1)


Bạn chạy script cú pháp như thế nào? Dưới đây là cú pháp đúng cho việc get_link
folder_downloader.py get_link "https://www.fshare.vn/file/QAYQK9DQC6L9"
hoặc folder_downloader.py get_link "https://www.fshare.vn/file/QAYQK9DQC6L9|blablabla<https://www.fshare.vn/file/QAYQK9DQC6L9%7Cblablabla>" vs link có password
